# Generated by Django 3.2.9 on 2021-12-04 20:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('line_number', models.IntegerField(blank=True, default=0, null=True)),
                ('line_content', models.TextField(blank=True, null=True)),
                ('line_length', models.IntegerField(default=0)),
                ('most_occurred_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_detail', to='file_upload.document')),
            ],
            options={
                'verbose_name': 'File Detail',
                'verbose_name_plural': 'File Details',
                'ordering': ('-line_length',),
            },
        ),
    ]
