# Generated by Django 3.2.9 on 2021-12-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='location',
            field=models.FileField(upload_to='file_upload_assets/'),
        ),
    ]
