# Generated by Django 3.2.9 on 2021-12-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PARSED', 'PARSED'), ('NON_PARSED', 'NON_PARSED')], default='NON_PARSED', max_length=24),
        ),
    ]
